name: Fetch and Cache Data

on:
  schedule:
    - cron: '*/10 13-15 * * *'  

jobs:
  fetch_and_cache_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch and cache data
      run: python fetch_data.py

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@example.com"
        git add docs/data.json
        git commit -m "Update data.json"
        git push
